#KubeJS Client Properties
#Mon Jan 06 21:21:44 MST 2025
backgroundColor=C59D1B
barBorderColor=C59D1B
exportAtlases=false
menuBackgroundBrightness=64
disableRecipeBook=true
title=Dark Ages
barColor=C59D1B
overrideColors=false
fmlLogColor=C59D1B
showTagNames=false
fmlMemoryColor=C59D1B
menuBackgroundScale=32.0
blurScaledPackIcon=true
menuInnerBackgroundBrightness=32
