
let groups = [
	'#another_furniture:benches',
	'#another_furniture:chairs',
	'#another_furniture:curtains',
	'#another_furniture:drawers',
	'#another_furniture:flower_boxes',
	'#another_furniture:shelves',
	'#another_furniture:shutters',
	'#another_furniture:sofas',
	'#another_furniture:stools',
	'#another_furniture:tables',
	'#another_furniture:tall_stools',
	'#c:glass_blocks',
	'#curios:spellbook',
	"#darkages:tents",
	'#darkages:amethyst',
	'#darkages:corals',
	'#darkages:dirt',
	'#darkages:fishing_items',
	'#darkages:generic_tools',
	'#darkages:gifts',
	'#darkages:leaf_carpets',
	'#darkages:leaf_hedges',
	'#darkages:navigation_tools',
	'#darkages:plants',
	'#darkages:shrooms',
	'#darkages:skillbooks',
	'#darkages:smithing_items',
	"#darkages:wagon_parts",
	"#darkages:metal_plates",
	"#darkages:heated_ingots",
	'#darkages:wooden_vertical_slabs',
	'#dragnlivestock:saddle',
	'#forge:bookshelves',
	'#forge:chests',
	'#forge:glass_panes',
	'#minecraft:arrows',
	'#minecraft:axes',
	'#minecraft:hoes',
	'#minecraft:music_discs',
	'#minecraft:pickaxes',
	'#minecraft:shovels',
	'#quark:framed_glasses',
	'#quark:hollow_logs',
	'#quark:ladders',
	'#quark:posts',
	'#smallships:ships',
	'#supplementaries:awnings',
	'#supplementaries:candle_holders',
	'#supplementaries:flags',
	'#supplementaries:presents',
	'#supplementaries:sign_posts',
	'#supplementaries:trapped_presents',
	'#travelersbackpack:custom_travelers_backpack',
	'#darkages:bedrolls',
	"#darkages:anvils",
	"#darkages:awnings",
	"#darkages:bows",
	"#darkages:bricks",
	"#darkages:carts",
	"#darkages:cooking",
	"#darkages:desserts",
	"#darkages:desserts",
	"#darkages:drinks",
	"#darkages:frames",
	"#darkages:furnaces",
	"#darkages:gems",
	"#darkages:grain",
	"#darkages:gutter_downspouts",
	"#darkages:gutters",
	"#darkages:hearty_meals",
	"#darkages:inks",
	"#darkages:meals",
	"#darkages:meat_cuts",
	"#darkages:plows",
	"#darkages:potion_ingredients",
	"#darkages:rarity_materials",
	"#darkages:raw_materials",
	"#darkages:rice",
	"#darkages:roofs/attic_roofs",
	"#darkages:roofs/lower_roofs",
	"#darkages:roofs/standard_roofs",
	"#darkages:roofs/steep_roofs",
	"#darkages:roofs/top_roofs",
	"#darkages:roofs/upper_lower_roofs",
	"#darkages:roofs/upper_steep_roofs",
	"#darkages:salads",
	"#darkages:seafood",
	"#darkages:soups_and_stews",
	"#darkages:vegetables",
	"#darkages:wagons",
	"#darkages:oils",
	"#darkages:oil_vials",
	"#darkages:fruits",
	"#darkages:poisonous_and_rotten",
	"#darkages:light_blocks",
	"#darkages:temperature_blocks",
	"#darkages:workstations",
	"#darkages:herbs",
	"#darkages:backpack_upgrades",
	"#darkages:stone_vertical_slabs"
]

groups.forEach(group => {
	let name = group.split(':')[1]
	// console.log(`Registering name: ${name} for tag: ${group}`)
	EmiPlusPlusEvents.registerGroups(event => {
		event.register(name, group)
	})
})

let armorgroups = [
	"#darkages:armor/leather_armor",
	"#darkages:armor/copper_armor",
	"#darkages:armor/chainmail_armor",
	"#darkages:armor/gold_armor",
	"#darkages:armor/silver_armor",
	"#darkages:armor/iron_armor",
	"#darkages:armor/steel_armor",
	"#darkages:armor/diamond_armor",
	"#darkages:armor/netherite_armor",
	"#darkages:armor/chess_armor",
	"#darkages:armor/crucible_armor",
	"#darkages:armor/dark_cover_armor",
	"#darkages:armor/dark_lord_armor",
	"#darkages:armor/gladiator_armor",
	"#darkages:armor/dragonslayer_armor",
	"#darkages:armor/eclipse_armor",
	"#darkages:armor/silent_armor",
	"#darkages:armor/flesh_of_the_feaster_armor",
	"#darkages:armor/fog_guard_armor",
	"#darkages:armor/forgotten_armor",
	"#darkages:armor/gilded_hunt_armor",
	"#darkages:armor/golden_execution_armor",
	"#darkages:armor/golden_horns_armor",
	"#darkages:armor/grave_sentinel_armor",
	"#darkages:armor/hero",
	"#darkages:armor/maria",
	"#darkages:armor/melania",
	"#darkages:armor/old_knight",
	"#darkages:armor/redeemer",
	"#darkages:armor/spark_of_dawn",
	"#darkages:armor/sunset_wings",
	"#darkages:armor/thief",
	"#darkages:armor/twinned",
	"#darkages:armor/wandering_wizard",
	"#darkages:armor/wind_worshipper",
	"#darkages:armor/amethyst_dragon_scale",
	"#darkages:armor/black_dragon_scale",
	"#darkages:armor/blue_dragon_scale",
	"#darkages:armor/bronze_dragon_scale",
	"#darkages:armor/copper_dragon_scale",
	"#darkages:armor/electric_blue_dragon_scale",
	"#darkages:armor/gray_dragon_scale",
	"#darkages:armor/green_dragon_scale",
	"#darkages:armor/red_dragon_scale",
	"#darkages:armor/sapphire_dragon_scale",
	"#darkages:armor/silver_dragon_scale",
	"#darkages:armor/electric_blue_dragon_scale",
	"#darkages:armor/white_dragon_scale",
	"#darkages:armor/red_chitin",
	"#darkages:armor/white_chitin",
	"#darkages:armor/tan_chitin",
	"#darkages:armor/fire_dragonsteel",
	"#darkages:armor/ice_dragonsteel",
	"#darkages:armor/lightning_dragonsteel",
	"#darkages:armor/forest_troll",
	"#darkages:armor/frost_troll",
	"#darkages:armor/mountain_troll",
	"#darkages:armor/desert_myrmex",
	"#darkages:armor/jungle_myrmex",
	"#darkages:armor/sheep_disguise",
	"#darkages:armor/blue_tide",
	"#darkages:armor/bronze_tide",
	"#darkages:armor/deep_blue_tide",
	"#darkages:armor/green_tide",
	"#darkages:armor/purple_tide",
	"#darkages:armor/red_tide",
	"#darkages:armor/teal_tide",
	"#darkages:armor/archevoker",
	"#darkages:armor/cryomancer",
	"#darkages:armor/cultist",
	"#darkages:armor/electromancer",
	"#darkages:armor/netherite_battlemage",
	"#darkages:armor/plague",
	"#darkages:armor/priest",
	"#darkages:armor/scarecrow",
	"#darkages:armor/pyromancer",
	"#darkages:armor/shadow_walker",
	"#darkages:armor/wandering_magician",
	"#darkages:armor/wizard",
	"#darkages:armor/snow",
	"#darkages:armor/desert",
	"#darkages:armor/dark_crusader",
	"#darkages:armor/dark_gothic",
	"#darkages:armor/dark_knight",
	"#darkages:armor/crusader",
	"#darkages:armor/verden",
	"#darkages:armor/aurelith",
	"#darkages:armor/solen",
	"#darkages:armor/redeemer",
	"#darkages:armor/roning",
	"#darkages:armor/ronin",
	"#darkages:armor/silver_knight",
	"#darkages:armor/orc"
]

armorgroups.forEach(armorgroup => {
	let name = armorgroup.split('/')[1]
	EmiPlusPlusEvents.registerGroups(event => {
		event.register(name, armorgroup)
	})
})

let weapongroups = [
	'#darkages:weapons/ahlspiesss',
	'#darkages:weapons/bastardswords',
	'#darkages:weapons/claymores',
	'#darkages:weapons/concavehalberds',
	'#darkages:weapons/daggers',
	'#darkages:weapons/estocs',
	'#darkages:weapons/greatswords',
	'#darkages:weapons/guisarmes',
	'#darkages:weapons/heavymaces',
	'#darkages:weapons/heavywarhammers',
	'#darkages:weapons/katzbalgers',
	'#darkages:weapons/lochaberaxes',
	'#darkages:weapons/longswords',
	'#darkages:weapons/lucernhammers',
	'#darkages:weapons/morgensterns',
	'#darkages:weapons/pikes',
	'#darkages:weapons/ranseurs',
	'#darkages:weapons/shortswords',
	'#darkages:weapons/spears',
	'#darkages:weapons/stylets',
	'#darkages:weapons/tachis',
	'#darkages:weapons/zweihanders'
]

weapongroups.forEach(weapongroup => {
	let name = weapongroup.split('/')[1]
	EmiPlusPlusEvents.registerGroups(event => {
		event.register(name, weapongroup)
	})
})

let shieldgroups = [
	"#darkages:shields/buckler",
	"#darkages:shields/elliptical_shield",
	"#darkages:shields/heater_shield",
	"#darkages:shields/kite_shield",
	"#darkages:shields/rondache",
	"#darkages:shields/round_shield",
	"#darkages:shields/targe"
]

shieldgroups.forEach(shieldgroup => {
	let name = shieldgroup.split('/')[1]
	EmiPlusPlusEvents.registerGroups(event => {
		event.register(name, shieldgroup)
	})
})